### ISSUE TITLE
System.MissingMethodException

### ISSUE THREAD

**Issue by Davilink** [jlucansky/Camunda.Api.Client#44] opened 2019-11-19 03:22 UTC
After investigation for few hours i finally found the reason of that exception.

This package is not compatible with refit version greater than 4.7.9 even if the Nuget dependencies doesn't specify it.

![image](https://user-images.githubusercontent.com/1498932/69113850-315d1000-0a52-11ea-93a0-758523627f99.png)

**Comment by Tom-Marlin-Spok** [comment] 2019-12-27 15:12
We also encountered this same problem. When using Refit version 4.7.9 in our project, the Camunda client worked fine. However, after upgrading to Refit version 5.0.33, we started seeing these "System.MissingMethodException" errors.

Here is the stack-trace:

>System.MissingMethodException : .ctor
>   at System.Reflection.CustomAttribute.FilterCustomAttributeRecord(CustomAttributeRecord caRecord, MetadataImport scope, Assembly& lastAptcaOkAssembly, RuntimeModule decoratedModule, MetadataToken decoratedToken, RuntimeType attributeFilterType, Boolean mustBeInheritable, Object[] attributes, IList derivedAttributes, RuntimeType& attributeType, IRuntimeMethodInfo& ctor, Boolean& ctorHasParameters, Boolean& isVarArg)
>   at System.Reflection.CustomAttribute.GetCustomAttributes(RuntimeModule decoratedModule, Int32 decoratedMetadataToken, Int32 pcaCount, RuntimeType attributeFilterType, Boolean mustBeInheritable, IList derivedAttributes)
>   at System.Reflection.CustomAttribute.GetCustomAttributes(RuntimeMethodInfo method, RuntimeType caType, Boolean inherit)
>   at Refit.RequestBuilderImplementation.AddInterfaceHttpMethods(Type interfaceType, Dictionary`2 methods) in d:\a\1\s\Refit\RequestBuilderImplementation.cs:line 65
>   at Refit.RequestBuilderImplementation..ctor(Type refitInterfaceType, RefitSettings refitSettings) in d:\a\1\s\Refit\RequestBuilderImplementation.cs:line 55
>   at Refit.RequestBuilderFactory.Create[T](RefitSettings settings) in d:\a\1\s\Refit\RequestBuilderFactory.cs:line 18
>   at Refit.RestService.For[T](HttpClient client, RefitSettings settings) in d:\a\1\s\Refit\RestService.cs:line 28
>   at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
>   at System.Lazy`1.ExecutionAndPublication(LazyHelper executionAndPublication, Boolean useDefaultConstructor)
>   at System.Lazy`1.CreateValue()
>   at Camunda.Api.Client.CamundaClient.get_Deployments()
... (our code here)


We were attempting to invoke this function:
>var deploymentInfo = await camunda.Deployments.Create($"{id}", true, false, "Workflow API", tenantId, new ResourceDataContent(content, $"{id}.bpmn"));

When we stepped through this on a debugger inside CamundaClient.cs, we see this code:
>public DeploymentService Deployments
>    {
>      get
>      {
>        return new DeploymentService(this._deploymentApi.Value);
>      }
>    }

In our case, the "_deploymentApi" was null.  We have not gotten a chance to debug any further.

To reproduce this issue:
1) Create a new project
2) Add the Refit Nuget package 5.0.33
3) Add the Camunda API client
4) Attempt to execute the camunda.Deployments.Create function.

**Comment by gaensebluemchenritter** [comment] 2020-02-15 15:27
The problems here start even earlier - when you try to build Camunda.Api.Client with Refit 5.x it fails for the CustomerUrlParameterFormatter. So, yes: Camunda.Api.Client as is is not compatible with Refit 5.x

Upgrading Camunda.Api.Client to Refit 5.x proves to be a bit of a challenge - as soon as I start to do that I get a ton of CS0246 errors with types/namespaces all of a sudden not known to net461. To mitigate that a little faster I tried to set the target framework to netstandard2.0

With that I get about the only breaking change of Refit that affects us directly. In CamundaClient.cs there is a CustomUrlParameterFormatter class (deriving from Refit.DefaultUrlParameterFormatter) with a now invalid method signature on Format.

Refactoring it to
`            public override string Format(object parameterValue, ICustomAttributeProvider attributeProvider, Type type)
            {
                if (parameterValue is bool)
                    return string.Format(CultureInfo.InvariantCulture, "{0}", parameterValue).ToLowerInvariant();

                return base.Format(parameterValue, attributeProvider, type);
            }
`
at least makes it compilable, following up with two warnings on Newtonsoft related stuff (gets automatically upgraded to 12.0.3) in StringEnumConverter.cs and CamundaClient.cs

You can find the changed code here:
https://github.com/gaensebluemchenritter/Camunda.Api.Client/commits/master

No guarantee it will work, right now I'm out of time ... and also I'm not entirely sure, why net461 is not working after applying the upgrade to Refit 5.0.23 (as it also defines a net461 target framework in its project file).

**Comment by gaensebluemchenritter** [comment] 2020-02-16 11:11
At a first glance (using our own project) it seems to work - please give it a try and feedback! Thanks!

**Comment by Tom-Marlin-Spok** [comment] 2020-02-17 17:53
> Solved the aforementioned problem with net461, so the changed code is compatible with both target frameworks again.
> 
> At a first glance (using our own project) it seems to work - please give it a try and feedback! Thanks!

Thanks for your help on this. Using your package, it did get further, but am now running into problems with querying for a specific ProcessDefinition.  Specifically, our code does this:

```
var processDefinitionList = await _camundaClient.ProcessDefinitions.Query(new ProcessDefinitionQuery
            {
                DeploymentId = deploymentId,
            }).List();
```

This fails with the info below:


```
Microsoft.CSharp.RuntimeBinder.RuntimeBinderException : 'Camunda.Api.Client.ProcessDefinition.AutoGeneratedIProcessDefinitionRestService' does not contain a definition for 'GetList'

   at CallSite.Target(Closure , CallSite , Object , ProcessDefinitionQuery , Object , Object )
   at System.Dynamic.UpdateDelegates.UpdateAndExecute4[T0,T1,T2,T3,TRet](CallSite site, T0 arg0, T1 arg1, T2 arg2, T3 arg3)
   at Camunda.Api.Client.QueryResource`2.List() in C:\Users\tom.marlin\git\spok\branches-workflow\aws-workflow\src\Camunda.Api.Client\Camunda.Api.Client\QueryResource.cs:line 20
... (our code here)
```

Our app uses .NET Core 2.2. I'm not sure if that's causing any of the problems or not.

**Comment by gaensebluemchenritter** [comment] 2020-02-18 10:00
I get the same problem, I was a bit over-eager  ;(

Fot that I need to delve deeper into Refit (and probably Reflection, urgh) to understand the underlying problem. The change to 5.x obviously brought some significant changes ...

**Comment by gaensebluemchenritter** [comment] 2020-02-18 16:43
First: a huge thank you to ckadluba for his invaluable help!

After some extensive debugging we found out, that from Refit 4.6.99 onwards QueryResource would not work. The private dynamic _api led to a problem deep inside the framework code (Reflection not being able to handle it correctly and the delegation code than not working).

Since we were unable to make the dynamic property work, we decided to use lambda expressions instead and changed the QueryResource constructor to accept Funcs as parameters instead of an api interface. Updating a "ton" of Service classes we also added a missing GetListCount in one of the History-Services.

This is a non breaking change for the user code, so it should pose no problems with your code. This time it definitely works with our project code (I checked the actual results)!

You can find the latest code at my repository - please give it a shot and report any problems you find!

https://github.com/gaensebluemchenritter/Camunda.Api.Client/tree/master

**Comment by ckadluba** [comment] 2020-02-19 15:49
> First: a huge thank you to ckadluba for his invaluable help!

Thank you @gaensebluemchenritter for the nice words. 😊 

@Tom-Marlin-Spok could you get the changes from his fork and try them in your application? If the fix works for you too, we could sketch out a PR.

**Comment by gaensebluemchenritter** [comment] 2020-04-24 07:35
@Tom-Marlin-Spok @Davilink @jlucansky @ckadluba 
I tried those changes with the latest version of our own project and it works without a problem. Of course, we are only using a small subset of functions exposed by the API, but getting process definitions, getting running instances, starting new process instances, fetching and locking external tasks, completing external tasks are to me a basis to make the educated guess that this actually works.

Nonetheless additional testing and code review by other people would be great to back this up - so it would be great to get some further feedback before making a pull request

**Comment by Davilink** [comment] 2020-04-24 07:41
Sadly, we needed a Camunda client for our project and couldn't wait for the this issue to be resolved, so we had to create our own Camunda client.

**Comment by gaensebluemchenritter** [comment] 2020-04-24 10:30
@Tom-Marlin-Spok @Davilink @jlucansky @ckadluba 
Just as a sidenote: did the upgrade to latest Refit version (5.1.67), tested it with our project and pushed it to my master branch (linked above). This gives us the option to upgrade Camunda.Api.Client to Systm.Text.Json instead of Newtonsoft, which rather than not would mean a performance gain and a smaller memory footprint. For new I sticked with Newtonsoft.

**Comment by gaensebluemchenritter** [comment] 2020-05-06 07:36
@jlucansky @ckadluba @Tom-Marlin-Spok 

After initiating a Pull Request (#55) the automated AppVeyor build (using msbuild 15.something) failed with a weird reference to an old version of System.Runtime.CompilerServices.Unsafe that I could not solve for now.

So I had to revert to Refit 5.0.23 for now, which does not yet use System.Text.Json (and therefor abovementioned package).

With msbuild 16.5.something as used by the latest version of VS 2019 there is no problem resolving the dependencies correctly, so perhaps it could be possible to reconfigure the automated build step?

**Closed** 2020-06-19 14:51 UTC
Labels: help wanted
